// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: coordinatex/v1/geo.proto

package coordinatexpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LatLng is a WGS84 point in decimal degrees.
type LatLng struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatLng) Reset() {
	*x = LatLng{}
	mi := &file_coordinatex_v1_geo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatLng) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatLng) ProtoMessage() {}

func (x *LatLng) ProtoReflect() protoreflect.Message {
	mi := &file_coordinatex_v1_geo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatLng.ProtoReflect.Descriptor instead.
func (*LatLng) Descriptor() ([]byte, []int) {
	return file_coordinatex_v1_geo_proto_rawDescGZIP(), []int{0}
}

func (x *LatLng) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *LatLng) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

// Bounds is a latitude/longitude box. min_lng > max_lng means it crosses the antimeridian.
type Bounds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinLat        float64                `protobuf:"fixed64,1,opt,name=min_lat,json=minLat,proto3" json:"min_lat,omitempty"`
	MinLng        float64                `protobuf:"fixed64,2,opt,name=min_lng,json=minLng,proto3" json:"min_lng,omitempty"`
	MaxLat        float64                `protobuf:"fixed64,3,opt,name=max_lat,json=maxLat,proto3" json:"max_lat,omitempty"`
	MaxLng        float64                `protobuf:"fixed64,4,opt,name=max_lng,json=maxLng,proto3" json:"max_lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bounds) Reset() {
	*x = Bounds{}
	mi := &file_coordinatex_v1_geo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bounds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bounds) ProtoMessage() {}

func (x *Bounds) ProtoReflect() protoreflect.Message {
	mi := &file_coordinatex_v1_geo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bounds.ProtoReflect.Descriptor instead.
func (*Bounds) Descriptor() ([]byte, []int) {
	return file_coordinatex_v1_geo_proto_rawDescGZIP(), []int{1}
}

func (x *Bounds) GetMinLat() float64 {
	if x != nil {
		return x.MinLat
	}
	return 0
}

func (x *Bounds) GetMinLng() float64 {
	if x != nil {
		return x.MinLng
	}
	return 0
}

func (x *Bounds) GetMaxLat() float64 {
	if x != nil {
		return x.MaxLat
	}
	return 0
}

func (x *Bounds) GetMaxLng() float64 {
	if x != nil {
		return x.MaxLng
	}
	return 0
}

// Circle is every point within radius_meters of center.
type Circle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Center        *LatLng                `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	RadiusMeters  float64                `protobuf:"fixed64,2,opt,name=radius_meters,json=radiusMeters,proto3" json:"radius_meters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Circle) Reset() {
	*x = Circle{}
	mi := &file_coordinatex_v1_geo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Circle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Circle) ProtoMessage() {}

func (x *Circle) ProtoReflect() protoreflect.Message {
	mi := &file_coordinatex_v1_geo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Circle.ProtoReflect.Descriptor instead.
func (*Circle) Descriptor() ([]byte, []int) {
	return file_coordinatex_v1_geo_proto_rawDescGZIP(), []int{2}
}

func (x *Circle) GetCenter() *LatLng {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *Circle) GetRadiusMeters() float64 {
	if x != nil {
		return x.RadiusMeters
	}
	return 0
}

// Polyline is an ordered sequence of points (route, track).
type Polyline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*LatLng              `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Polyline) Reset() {
	*x = Polyline{}
	mi := &file_coordinatex_v1_geo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Polyline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Polyline) ProtoMessage() {}

func (x *Polyline) ProtoReflect() protoreflect.Message {
	mi := &file_coordinatex_v1_geo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Polyline.ProtoReflect.Descriptor instead.
func (*Polyline) Descriptor() ([]byte, []int) {
	return file_coordinatex_v1_geo_proto_rawDescGZIP(), []int{3}
}

func (x *Polyline) GetPoints() []*LatLng {
	if x != nil {
		return x.Points
	}
	return nil
}

// Ring is a polygon ring; closing the ring is optional.
type Ring struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*LatLng              `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ring) Reset() {
	*x = Ring{}
	mi := &file_coordinatex_v1_geo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ring) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ring) ProtoMessage() {}

func (x *Ring) ProtoReflect() protoreflect.Message {
	mi := &file_coordinatex_v1_geo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ring.ProtoReflect.Descriptor instead.
func (*Ring) Descriptor() ([]byte, []int) {
	return file_coordinatex_v1_geo_proto_rawDescGZIP(), []int{4}
}

func (x *Ring) GetPoints() []*LatLng {
	if x != nil {
		return x.Points
	}
	return nil
}

// Polygon is an exterior ring with optional holes.
type Polygon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outer         *Ring                  `protobuf:"bytes,1,opt,name=outer,proto3" json:"outer,omitempty"`
	Holes         []*Ring                `protobuf:"bytes,2,rep,name=holes,proto3" json:"holes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Polygon) Reset() {
	*x = Polygon{}
	mi := &file_coordinatex_v1_geo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Polygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Polygon) ProtoMessage() {}

func (x *Polygon) ProtoReflect() protoreflect.Message {
	mi := &file_coordinatex_v1_geo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Polygon.ProtoReflect.Descriptor instead.
func (*Polygon) Descriptor() ([]byte, []int) {
	return file_coordinatex_v1_geo_proto_rawDescGZIP(), []int{5}
}

func (x *Polygon) GetOuter() *Ring {
	if x != nil {
		return x.Outer
	}
	return nil
}

func (x *Polygon) GetHoles() []*Ring {
	if x != nil {
		return x.Holes
	}
	return nil
}

var File_coordinatex_v1_geo_proto protoreflect.FileDescriptor

const file_coordinatex_v1_geo_proto_rawDesc = "" +
	"\n" +
	"\x18coordinatex/v1/geo.proto\x12\x0ecoordinatex.v1\",\n" +
	"\x06LatLng\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\"l\n" +
	"\x06Bounds\x12\x17\n" +
	"\amin_lat\x18\x01 \x01(\x01R\x06minLat\x12\x17\n" +
	"\amin_lng\x18\x02 \x01(\x01R\x06minLng\x12\x17\n" +
	"\amax_lat\x18\x03 \x01(\x01R\x06maxLat\x12\x17\n" +
	"\amax_lng\x18\x04 \x01(\x01R\x06maxLng\"]\n" +
	"\x06Circle\x12.\n" +
	"\x06center\x18\x01 \x01(\v2\x16.coordinatex.v1.LatLngR\x06center\x12#\n" +
	"\rradius_meters\x18\x02 \x01(\x01R\fradiusMeters\":\n" +
	"\bPolyline\x12.\n" +
	"\x06points\x18\x01 \x03(\v2\x16.coordinatex.v1.LatLngR\x06points\"6\n" +
	"\x04Ring\x12.\n" +
	"\x06points\x18\x01 \x03(\v2\x16.coordinatex.v1.LatLngR\x06points\"a\n" +
	"\aPolygon\x12*\n" +
	"\x05outer\x18\x01 \x01(\v2\x14.coordinatex.v1.RingR\x05outer\x12*\n" +
	"\x05holes\x18\x02 \x03(\v2\x14.coordinatex.v1.RingR\x05holesB5Z3github.com/bakhod1r/coordinatex/proto/coordinatexpbb\x06proto3"

var (
	file_coordinatex_v1_geo_proto_rawDescOnce sync.Once
	file_coordinatex_v1_geo_proto_rawDescData []byte
)

func file_coordinatex_v1_geo_proto_rawDescGZIP() []byte {
	file_coordinatex_v1_geo_proto_rawDescOnce.Do(func() {
		file_coordinatex_v1_geo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coordinatex_v1_geo_proto_rawDesc), len(file_coordinatex_v1_geo_proto_rawDesc)))
	})
	return file_coordinatex_v1_geo_proto_rawDescData
}

var file_coordinatex_v1_geo_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_coordinatex_v1_geo_proto_goTypes = []any{
	(*LatLng)(nil),   // 0: coordinatex.v1.LatLng
	(*Bounds)(nil),   // 1: coordinatex.v1.Bounds
	(*Circle)(nil),   // 2: coordinatex.v1.Circle
	(*Polyline)(nil), // 3: coordinatex.v1.Polyline
	(*Ring)(nil),     // 4: coordinatex.v1.Ring
	(*Polygon)(nil),  // 5: coordinatex.v1.Polygon
}
var file_coordinatex_v1_geo_proto_depIdxs = []int32{
	0, // 0: coordinatex.v1.Circle.center:type_name -> coordinatex.v1.LatLng
	0, // 1: coordinatex.v1.Polyline.points:type_name -> coordinatex.v1.LatLng
	0, // 2: coordinatex.v1.Ring.points:type_name -> coordinatex.v1.LatLng
	4, // 3: coordinatex.v1.Polygon.outer:type_name -> coordinatex.v1.Ring
	4, // 4: coordinatex.v1.Polygon.holes:type_name -> coordinatex.v1.Ring
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_coordinatex_v1_geo_proto_init() }
func file_coordinatex_v1_geo_proto_init() {
	if File_coordinatex_v1_geo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coordinatex_v1_geo_proto_rawDesc), len(file_coordinatex_v1_geo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coordinatex_v1_geo_proto_goTypes,
		DependencyIndexes: file_coordinatex_v1_geo_proto_depIdxs,
		MessageInfos:      file_coordinatex_v1_geo_proto_msgTypes,
	}.Build()
	File_coordinatex_v1_geo_proto = out.File
	file_coordinatex_v1_geo_proto_goTypes = nil
	file_coordinatex_v1_geo_proto_depIdxs = nil
}
